# Generated by Django 5.2 on 2025-04-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('video_url', models.URLField(verbose_name='Video havolasi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name="Oldindan ko'rinish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
            ],
            options={
                'verbose_name': 'Qiziqarli video',
                'verbose_name_plural': 'Qiziqarli videolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
