# Generated by Django 5.2 on 2025-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiziktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, verbose_name='Vaqt chegarasi (sekund)'),
        ),
    ]
