# Generated by Django 5.2 on 2025-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiziktest', '0002_alter_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='fiziktest.question', verbose_name='Savollar'),
        ),
    ]
