# Generated by Django 5.2 on 2025-04-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('problem_text', models.TextField(verbose_name='Masala matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='practical_tasks/', verbose_name='Rasm')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Yechim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_tasks', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "Amaliy mashg'ulot",
                'verbose_name_plural': "Amaliy mashg'ulotlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
