# Generated by Django 5.2 on 2025-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maruza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='google_docs_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Docs havolasi'),
        ),
    ]
