# Generated by Django 5.2 on 2025-04-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=20, verbose_name='Qiyinlik darajasi')),
            ],
            options={
                'verbose_name': 'Krossvord',
                'verbose_name_plural': 'Krossvordlar',
            },
        ),
        migrations.CreateModel(
            name='WordGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.CharField(max_length=50, verbose_name='Javob')),
                ('hint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yordam')),
            ],
            options={
                'verbose_name': "So'z o'yini",
                'verbose_name_plural': "So'z o'yinlari",
            },
        ),
        migrations.CreateModel(
            name='CrosswordClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Raqam')),
                ('clue', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.CharField(max_length=50, verbose_name='Javob')),
                ('row', models.IntegerField(verbose_name='Satr')),
                ('col', models.IntegerField(verbose_name='Ustun')),
                ('direction', models.CharField(choices=[('across', 'Gorizontal'), ('down', 'Vertikal')], max_length=10, verbose_name="Yo'nalish")),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='krossvord.crossword')),
            ],
            options={
                'verbose_name': 'Krossvord savoli',
                'verbose_name_plural': 'Krossvord savollari',
                'ordering': ['number'],
            },
        ),
    ]
