# Generated by Django 5.2 on 2025-04-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krossvord', '0001_initial'),
    ]

    operations = [
    ]
