# Generated by Django 5.2 on 2025-04-27 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation_games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('iframe_url', models.URLField(verbose_name='Simulyatsiya URL manzili')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='simulation_games/', verbose_name="Oldindan ko'rinish tasviri")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_games', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
            ],
            options={
                'verbose_name': "Simulyatsion o'yin",
                'verbose_name_plural': "Simulyatsion o'yinlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
