# Generated by Django 5.2 on 2025-04-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='projects/', verbose_name='Fayl')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Topshirilgan'), ('reviewed', "Ko'rib chiqilgan"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Baho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_projects', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
