# Generated by Django 5.2 on 2025-04-27 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('instructions', models.TextField(verbose_name="Ko'rsatmalar")),
                ('simulation_url', models.URLField(blank=True, null=True, verbose_name='Simulyatsiya havolasi')),
                ('file', models.FileField(blank=True, null=True, upload_to='laboratory/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Laboratoriya ishi',
                'verbose_name_plural': 'Laboratoriya ishlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
