# Generated by Django 5.2 on 2025-04-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaratoriya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='google_docs_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Docs havolasi'),
        ),
    ]
